/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fionn.blacky_heart

import com.fionn.blacky_heart.config.Configuration
import com.fionn.blacky_heart.core.application.services.GuildDeleteService
import com.fionn.blacky_heart.core.application.services.GuildRegisterService
import com.fionn.blacky_heart.core.application.services.GuildSyncService
import com.fionn.blacky_heart.core.application.transaction.TransactionScope
import com.fionn.blacky_heart.core.domain.repositories.GuildRepository
import com.fionn.blacky_heart.core.infrastructure.repositories.GuildRepositoryImpl
import com.fionn.blacky_heart.core.infrastructure.transaction.TransactionScopeImpl
import com.fionn.blacky_heart.core.presentation.listeners.GuildJoinListener
import com.fionn.blacky_heart.core.presentation.listeners.GuildLeaveListener
import com.fionn.blacky_heart.core.presentation.listeners.ReadyListener
import org.kodein.di.DI
import org.kodein.di.bind
import org.kodein.di.instance
import org.kodein.di.singleton

class App {
    private val di: DI = DI {
        bind<BlackyHeart>() with singleton {
            BlackyHeart(
                instance(),
                instance(),
                instance(),
                instance(),
            )
        }
        bind<Configuration>() with singleton { Configuration.load() }
        bind<TransactionScope>() with singleton { TransactionScopeImpl() }
        bind<ReadyListener>() with singleton { ReadyListener(instance()) }
        bind<GuildJoinListener>() with singleton { GuildJoinListener(instance()) }
        bind<GuildLeaveListener>() with singleton { GuildLeaveListener(instance()) }
        bind<GuildRegisterService>() with singleton { GuildRegisterService(instance(), instance(), instance()) }
        bind<GuildDeleteService>() with singleton { GuildDeleteService(instance(), instance()) }
        bind<GuildSyncService>() with singleton { GuildSyncService(instance(), instance(), instance()) }
        bind<GuildRepository>() with singleton { GuildRepositoryImpl() }
    }

    fun run() {
        val blackyHeart: BlackyHeart by di.instance()

        blackyHeart.start()
    }
}

fun main() {
    App().run()
}
