/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fionn.blacky_heart

class App {
    fun run() {
        val blackyHeart = BlackyHeart()

        blackyHeart.start()
    }
}

fun main() {
    App().run()
}
