/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fionn.blacky_heart

import kotlin.reflect.full.declaredFunctions
import kotlin.test.DefaultAsserter.assertTrue
import kotlin.test.Test

class AppTest {
    @Test fun hasRunMethod() {
        val methodNames: List<String> = App::class.declaredFunctions.map { it.name }
        assertTrue("Method 'run' does not exist", methodNames.contains("run"))
    }
}
